### ISSUE TITLE
Field `ondemand` missing from Table Schema

### ISSUE THREAD

**Issue by md5577** [tuxudo/launchdaemons#1]
Hello, 

After the initial deployment of the module, the Listing 'Launch Daemons' displays the error: 
```
DataTables warning: table id=DataTables_Table_0 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'launchdaemons.ondemand' in 'field list'
```

Is the field `ondemand` required to be used in the table `launchdaemons`? I don't see it listed in the Table Schema. 

Let me know if you have any insight. 
Thank you.

**Comment by tuxudo** [comment]
That column is a part of the table schema, but was omitted from the readme. That has been corrected. Did you run the database migrations after enabling the module?

**Comment by md5577** [comment]
Hi, 
Thank you for the response. I'm new to MunkiReport and this is my first custom module installation following the document: https://github.com/munkireport/munkireport-php/wiki/Module-Overview

I've created the SQL table and fields manually so far. 
I would appreciate a response to the following: 
1. I've tried running (what I assumed is) the migration command and encountered an error (Ubuntu 18.04LTS): 
```
$ sudo php /var/munkireport/vendor/tuxudo/launchdaemons/migrations/2019_02_23_000001_launchdaemons_rewrite.php

PHP Fatal error:  Uncaught Error: Class 'Illuminate\Database\Migrations\Migration' not found in /var/munkireport/vendor/tuxudo/launchdaemons/migrations/2019_02_23_000001_launchdaemons_rewrite.php:6
Stack trace:
#0 {main}
```
1. How do I run a migration? 
2. Is the migration required to be performed manually after each module upgrade to the next version? 

Thank you.

**Comment by tuxudo** [comment]
I strongly suggest that you start with a completely new database. After you've dropped all the existing tables from your munkireport database, follow the instructions here to run the migrations: https://github.com/munkireport/munkireport-php/wiki/General-Upgrade-Procedures#run-migrations

It is important to run the migrations every time you update or change a module.

**Comment by md5577** [comment]
Hi, 
Dropping all the tables and running the `migrate` command recreated all the tables including those for the custom module. 
Thanks a lot for the support.
